# File: scripts/replay.py
"""A36: replay saved source outputs through mapper + aggregator. Zero Azure calls.

  python3 scripts/replay.py --report                 baseline table
  python3 scripts/replay.py --report --out docs/FIELD_TEST_REPLAY.md
  python3 scripts/replay.py --mapper-module app.mapper --aggregator-module app.aggregator
  python3 scripts/replay.py --unmapped server/eval/runs/unmapped_tags.json
"""
from __future__ import annotations

import argparse
import importlib
import json
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "server"))
SOURCES = ROOT / "server" / "eval" / "runs" / "sources.jsonl"
NAMES = {"local": "local_onnx", "azure": "azure"}


def load_rows(path: Path) -> list[dict]:
    rows = []
    for line in path.read_text("utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def predict(row: dict, mapper, agg) -> dict:
    """One photo -> {status, top, ranked_ids, hazard_id}. top is None when nothing matched."""
    usable = {}
    for key, name in NAMES.items():
        pairs = [(t["label"], t["score"]) for t in (row.get(key) or [])]
        scores = mapper.map_labels(pairs) if pairs else {}
        if scores:
            usable[name] = scores
    if not usable:
        return {"status": "uncertain", "top": None, "ranked": [], "hazard_id": None}
    d = agg.decide(usable)
    ranked = [d.category_id] if d.category_id else []
    ranked += [c for c, _ in d.alternatives if c not in ranked]
    return {"status": d.status, "top": ranked[0] if ranked else None, "ranked": ranked,
            "hazard_id": d.hazard_id}


def metrics(rows: list[dict], mapper, agg) -> dict:
    n = len(rows)
    hits = Counter()
    conf: dict[str, Counter] = defaultdict(Counter)
    haz_total = haz_found = 0
    group_of = agg.GROUP_OF
    for r in rows:
        truth, p = r["truth"], predict(r, mapper, agg)
        top = p["top"]
        conf[truth][top or "(none)"] += 1
        ok = p["status"] == "ok"
        hits["uncertain"] += not ok
        hits["top1"] += top == truth
        hits["top2"] += truth in p["ranked"][:2]
        hits["group"] += bool(top) and group_of.get(top) == group_of.get(truth)
        if ok:
            hits["ok"] += 1
            hits["ok_right"] += top == truth
            hits["conf_wrong"] += top != truth
        if truth in agg.HAZARD_IDS:
            haz_total += 1
            haz_found += top == truth or p["hazard_id"] == truth
    pct = lambda a, b: round(100.0 * a / b, 1) if b else None  # noqa: E731
    return {
        "photos": n, "top1": pct(hits["top1"], n), "top2_recall": pct(hits["top2"], n),
        "group_accuracy": pct(hits["group"], n), "uncertain": pct(hits["uncertain"], n),
        "ok_count": hits["ok"], "accuracy_on_ok": pct(hits["ok_right"], hits["ok"]),
        "confident_wrong": pct(hits["conf_wrong"], n),
        "hazard_recall": pct(haz_found, haz_total), "hazard_photos": haz_total,
        "confusion": {t: dict(c) for t, c in sorted(conf.items())},
    }


def unmapped(rows: list[dict], mapper) -> list[dict]:
    rules, cnt = mapper.load_rules(), Counter()
    for r in rows:
        for t in r.get("azure") or []:
            if not mapper._weights(t["label"], rules):
                cnt[t["label"].strip().lower()] += 1
    return [{"tag": k, "count": v} for k, v in cnt.most_common()]


def table(m: dict) -> str:
    keys = ["photos", "top1", "top2_recall", "group_accuracy", "accuracy_on_ok",
            "confident_wrong", "uncertain", "hazard_recall", "hazard_photos"]
    lines = ["| Metric | Value |", "|---|---|"]
    lines += [f"| {k} | {m[k]}{'' if k in ('photos', 'hazard_photos') else ' %'} |" for k in keys]
    return "\n".join(lines)


def confusion_md(m: dict) -> str:
    out = ["| Truth | Predicted (count) |", "|---|---|"]
    for t, c in m["confusion"].items():
        out.append(f"| {t} | " + ", ".join(f"{k}: {v}" for k, v in sorted(c.items(), key=lambda kv: -kv[1])) + " |")
    return "\n".join(out)


def report_md(m: dict, label: str) -> str:
    return (f"<!-- File: docs/FIELD_TEST_REPLAY.md -->\n# Field test replay ({label})\n\n"
            f"Generated by `scripts/replay.py` on {date.today()}. Source outputs captured once "
            f"by `scripts/capture_sources.py`; no Azure calls during replay. "
            f"Sample size: {m['photos']} photos.\n\n## Metrics\n{table(m)}\n\n"
            f"## Confusion (truth -> predicted)\n{confusion_md(m)}\n")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sources", type=Path, default=SOURCES)
    ap.add_argument("--mapper-module", default="app.mapper")
    ap.add_argument("--aggregator-module", default="app.aggregator")
    ap.add_argument("--label", default="baseline: current mapper and aggregator")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--out", type=Path)
    ap.add_argument("--unmapped", type=Path)
    a = ap.parse_args(argv)
    if not a.sources.is_file():
        print(f"FAIL: {a.sources} missing (run scripts/capture_sources.py first)")
        return 1
    rows = load_rows(a.sources)
    mapper = importlib.import_module(a.mapper_module)
    agg = importlib.import_module(a.aggregator_module)
    m = metrics(rows, mapper, agg)
    if a.unmapped:
        a.unmapped.parent.mkdir(parents=True, exist_ok=True)
        a.unmapped.write_text(json.dumps({"tags": unmapped(rows, mapper)}, indent=1), "utf-8")
        print(f"unmapped tags written to {a.unmapped}")
    if a.report or not (a.out or a.unmapped):
        print(table(m))
        if m["photos"] < 100:
            print(f"WARNING: only {m['photos']} photos; G-A needs 100+")
    if a.out:
        a.out.write_text(report_md(m, a.label), "utf-8")
        print(f"report written to {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
